<?php
$db = mysql_connect("argo.beget.ru", "ivanyu_bd", "ufkzytctdjle");
mysql_query("SET CHARACTER SET 'utf8'", $db);
mysql_select_db("ivanyu_bd", $db);

function latrus ($string) 
{
$string = ereg_replace("Final","файнал",$string);  
$string = ereg_replace("final","файнал",$string);  
$string = ereg_replace("Beautiful","бютифул",$string);  
$string = ereg_replace("Just","джаст",$string);
$string = ereg_replace("official","",$string);
$string = ereg_replace("Official","",$string);
$string = ereg_replace("just","джаст",$string);
$string = ereg_replace("happy","хеппи",$string);//ose  
$string = ereg_replace("riends","рендс",$string);
$string = ereg_replace("ge ","дж ",$string);
$string = ereg_replace("ge","ге",$string);
$string = ereg_replace("Life","лайф",$string); 
$string = ereg_replace("ely ","ли ",$string); 
$string = ereg_replace("ore ","ор ",$string); 
$string = ereg_replace("done","дан",$string);
$string = ereg_replace("gic ","джик ",$string);
$string = ereg_replace("Happy","хеппи",$string);
$string = ereg_replace("beautiful","бютифул",$string);//     happy  Oh  Lose 
$string = ereg_replace("day","дей",$string);
$string = ereg_replace("Some","сам",$string);
$string = ereg_replace("ard","ард",$string);
$string = ereg_replace("ve ","в ",$string);//  Smile side
$string = ereg_replace("de ","д ",$string);// 
$string = ereg_replace("Smile","смайл",$string);//   
$string = ereg_replace("friend","френд",$string);
$string = ereg_replace("Friend","френд",$string);
$string = ereg_replace("thm ","тм ",$string);
$string = ereg_replace("re ","р ",$string);//
$string = ereg_replace("wind","винд",$string);//
$string = ereg_replace("ind","айнд",$string);// 
$string = ereg_replace("ould","улд",$string);
$string = ereg_replace("ild","айлд",$string);
$string = ereg_replace("smile","смайл",$string);// music
$string = ereg_replace("music","мюзик",$string);
$string = ereg_replace("Music","мюзик",$string);
$string = ereg_replace("side","сайд",$string);
$string = ereg_replace("Side","сайд",$string);
$string = ereg_replace("Lose ","луз ",$string);// Kno
$string = ereg_replace("Kno","но",$string);
$string = ereg_replace("kno","но",$string);
$string = ereg_replace("While","вайл",$string);// 
$string = ereg_replace("dise","дайс",$string);// 
$string = ereg_replace("gle","гл",$string);
$string = ereg_replace("while","вайл",$string);// 
$string = ereg_replace("cy","си",$string);// 
$string = ereg_replace("le ","л ",$string);// 
$string = ereg_replace("Oh","о",$string);// 
$string = ereg_replace(" Lose "," луз ",$string);// 
$string = ereg_replace(" lose "," луз ",$string);// 
$string = ereg_replace("Through","сру",$string);
$string = ereg_replace("through","сру",$string);
$string = ereg_replace("ight","айт",$string);
$string = ereg_replace("City","сити",$string);
$string = ereg_replace("city","сити",$string);
$string = ereg_replace("cel","сел",$string);
$string = ereg_replace("Cel","сел",$string);
$string = ereg_replace(" AND "," енд ",$string);
$string = ereg_replace("ation","ейшин",$string);//
$string = ereg_replace("tion","шин",$string);
$string = ereg_replace("ph","ф",$string);//
$string = ereg_replace("Ph","ф",$string);//
$string = ereg_replace("Cry","край",$string);// 
$string = ereg_replace("cry","край",$string);// 
$string = ereg_replace("py ","пи ",$string);
$string = ereg_replace("right","райт",$string);
$string = ereg_replace("Right","райт",$string);
$string = ereg_replace("About","ебаут",$string);
$string = ereg_replace("about","ебаут",$string);
$string = ereg_replace("ky","ки",$string);
$string = ereg_replace(" Us "," ас ",$string);
$string = ereg_replace(" us "," ас ",$string);
$string = ereg_replace("have","хев",$string);
$string = ereg_replace("Have","хев",$string);
$string = ereg_replace("mind","майнд",$string);
$string = ereg_replace("Mind","майнд",$string);
$string = ereg_replace("Little","литл",$string);
$string = ereg_replace("little","литл",$string);
$string = ereg_replace("Without","визаут",$string);
$string = ereg_replace("without","визаут",$string);
$string = ereg_replace("Down","даун",$string);
$string = ereg_replace("down","даун",$string);
$string = ereg_replace("Now ","нау ",$string);
$string = ereg_replace(" Now "," нау ",$string);
$string = ereg_replace(" now "," нау ",$string);
$string = ereg_replace("ce","се",$string);//Super
$string = ereg_replace("Super","супер",$string);
$string = ereg_replace("super","супер",$string);
$string = ereg_replace("Dance","денс",$string);
$string = ereg_replace("dance","денс",$string);
$string = ereg_replace("Every","еври",$string);
$string = ereg_replace("every","еври",$string);
$string = ereg_replace("Heaven","хеван",$string);
$string = ereg_replace("heaven","хеван",$string);
$string = ereg_replace("Two","ту",$string);
$string = ereg_replace("two","ту",$string);
$string = ereg_replace("Try","трай",$string);  
$string = ereg_replace("try","трай",$string); 
$string = ereg_replace("Away","евей",$string);  
$string = ereg_replace("eway","евей",$string); 
$string = ereg_replace("ff","ф",$string); 
$string = ereg_replace("Make","мейк",$string); 
$string = ereg_replace("make","мейк",$string);
$string = ereg_replace("Night","найт",$string);
$string = ereg_replace("night","найт",$string);
$string = ereg_replace("By ","бай ",$string);
$string = ereg_replace("Pretty","прети",$string);
$string = ereg_replace("pretty","прети",$string);
$string = ereg_replace("Fly","флай",$string);
$string = ereg_replace("fly","флай",$string);
$string = ereg_replace("ly","ли",$string);
$string = ereg_replace("Ly","ли",$string);
$string = ereg_replace(" One "," ван ",$string);
$string = ereg_replace("One ","ван ",$string);
$string = ereg_replace(" one "," ван ",$string);
$string = ereg_replace("this","зис",$string);
$string = ereg_replace("This","зис",$string);
$string = ereg_replace("don","дон",$string);
$string = ereg_replace("Don","дон",$string);
$string = ereg_replace("The","зе",$string);
$string = ereg_replace("the","зе",$string);
$string = ereg_replace("girl","герл",$string);
$string = ereg_replace("Girl","герл",$string);
$string = ereg_replace("would","вуд",$string);
$string = ereg_replace("Would","вуд",$string);
$string = ereg_replace("Come","кам",$string);
$string = ereg_replace("come","кам",$string); // Any  U  геpл
$string = ereg_replace(" U "," ю ",$string); // 
$string = ereg_replace("Any","ени",$string); // 
$string = ereg_replace("any","ени",$string); // 
$string = ereg_replace("Change","чендж",$string);
$string = ereg_replace("Change","чендж",$string);
$string = ereg_replace("Girls","гелс",$string);
$string = ereg_replace("for","фо",$string);
$string = ereg_replace("For","фо",$string);
$string = ereg_replace("All","Ол",$string);
$string = ereg_replace("all","ол",$string);
$string = ereg_replace("girls","гелс",$string);
$string = ereg_replace("your","йо",$string);// When 
$string = ereg_replace("When","вен",$string);   
$string = ereg_replace("when","вен",$string); 
$string = ereg_replace("Take","тейк",$string);
$string = ereg_replace("take","тейк",$string);
$string = ereg_replace("ss","с",$string);
$string = ereg_replace("ie","и",$string);
$string = ereg_replace("Bad","бед",$string);
$string = ereg_replace(" Bad "," бед ",$string);
$string = ereg_replace(" bad "," бед ",$string);
$string = ereg_replace(" bad"," бед",$string);
$string = ereg_replace("Touch","тач",$string);
$string = ereg_replace("touch","тач",$string);
$string = ereg_replace("Young","янг",$string);
$string = ereg_replace("young","янг",$string);
$string = ereg_replace("Light","лайт",$string);
$string = ereg_replace("light","лайт",$string);
$string = ereg_replace("Can","кен",$string);
$string = ereg_replace("can","кен",$string);
$string = ereg_replace("eyes","айс",$string);
$string = ereg_replace("Eyes","айс",$string);
$string = ereg_replace("Move","мув",$string);
$string = ereg_replace("move","мув",$string);
$string = ereg_replace("ride","райд",$string);
$string = ereg_replace("people","пипл",$string); 
$string = ereg_replace("People","пипл",$string); 
$string = ereg_replace("Do ","ду ",$string);  
$string = ereg_replace("Always","олвейс",$string);
$string = ereg_replace("always","олвейс",$string);
$string = ereg_replace("Man","мен",$string);
$string = ereg_replace("ll","л",$string);
$string = ereg_replace("man","мен",$string);
$string = ereg_replace("Crazy","крейзи",$string);
$string = ereg_replace("crazy","крейзи",$string); 
$string = ereg_replace("Heart","харт",$string);
$string = ereg_replace("heart","харт",$string);
$string = ereg_replace("Like","лайк",$string);
$string = ereg_replace("like","лайк",$string);
$string = ereg_replace(" by "," бай ",$string);
$string = ereg_replace(" By "," бай ",$string);
$string = ereg_replace("ea","и",$string);
$string = ereg_replace("ose ","ос ",$string);
$string = ereg_replace("Ea","и",$string); //
$string = ereg_replace("lue","лю",$string);
$string = ereg_replace("Time","тайм",$string);
$string = ereg_replace("time","тайм",$string);
$string = ereg_replace("Your","Йо",$string);
$string = ereg_replace("Life","лайф",$string);
$string = ereg_replace("ya","я",$string);//  
$string = ereg_replace("ge ","ж ",$string);   
$string = ereg_replace("ge","ж",$string); 
$string = ereg_replace("lyn","лин",$string); //  
$string = ereg_replace("Live","лайв",$string);
$string = ereg_replace("live","лайв",$string);
$string = ereg_replace("hn","н",$string); 
$string = ereg_replace("life","лайф",$string); //Shy 
$string = ereg_replace("Shy","шай",$string);
$string = ereg_replace(" shy "," шай ",$string);
$string = ereg_replace("Guy","гай",$string);
$string = ereg_replace(" guy "," гай ",$string);
$string = ereg_replace(" say "," сей ",$string);
$string = ereg_replace(" Say "," сей ",$string); //My 
$string = ereg_replace(" My "," май ",$string);
$string = ereg_replace(" my "," май ",$string);
$string = ereg_replace("My ","май ",$string);
$string = ereg_replace(" My"," май",$string);
$string = ereg_replace(" a "," е ",$string); 
$string = ereg_replace(" A "," е ",$string); 
$string = ereg_replace(" are "," а ",$string); 
$string = ereg_replace(" Are "," а ",$string);
$string = ereg_replace("am","ем",$string);  
$string = ereg_replace("ful","фул",$string); 
$string = ereg_replace("tu","ту",$string);
$string = ereg_replace(" Do "," ду ",$string);
$string = ereg_replace(" do "," ду ",$string);
$string = ereg_replace(" Do"," ду",$string);
$string = ereg_replace(" do"," ду",$string);
$string = ereg_replace(" To "," ту ",$string);
$string = ereg_replace(" to "," ту ",$string);
$string = ereg_replace("ny","ни",$string);
$string = ereg_replace(" To"," ту",$string);
$string = ereg_replace(" To"," ту",$string);
$string = ereg_replace("You","ю",$string);
$string = ereg_replace("you","ю",$string);
$string = ereg_replace("zh","ж",$string);
$string = ereg_replace("That","зет",$string);
$string = ereg_replace("that","зет",$string);
$string = ereg_replace("Show","шоу",$string);
$string = ereg_replace("show","шоу",$string);
$string = ereg_replace("What","вот",$string);
$string = ereg_replace("what","вот",$string);
$string = ereg_replace(" Me "," ми ",$string);
$string = ereg_replace("ry","ри",$string);
$string = ereg_replace("dy","ди",$string);
$string = ereg_replace(" me "," ми ",$string);

$string = ereg_replace("Way","вей",$string);
$string = ereg_replace("way","вей",$string);
$string = ereg_replace("width","виз",$string);//
$string = ereg_replace("Width","виз",$string);
$string = ereg_replace(" Up "," ап ",$string);
$string = ereg_replace(" Up"," ап",$string);
$string = ereg_replace(" up "," ап ",$string);
$string = ereg_replace(" up"," ап",$string);
$string = ereg_replace("Bye","бай",$string);
$string = ereg_replace("bye","бай",$string);
$string = ereg_replace("I'll","ай вил",$string);
$string = ereg_replace("i'll","ай вил",$string);
$string = ereg_replace("Try","трай",$string);
$string = ereg_replace("try","трай",$string);
$string = ereg_replace("Out","аут",$string);
$string = ereg_replace("out","аут",$string);
$string = ereg_replace("There","зер",$string);//
$string = ereg_replace("there","зер",$string);//
$string = ereg_replace(" Be "," би ",$string);//
$string = ereg_replace(" be "," би ",$string);//
$string = ereg_replace("Be ","би ",$string);//
$string = ereg_replace("be ","би ",$string);//
$string = ereg_replace("I ","Ай ",$string);//
$string = ereg_replace("Sould","шуд",$string);//
$string = ereg_replace("sould","шуд",$string);//
$string = ereg_replace("don't","донт",$string);//
$string = ereg_replace("Don't","донт",$string);//
$string = ereg_replace("cky","ки",$string);//
$string = ereg_replace("ck","к",$string);//
$string = ereg_replace("ty","ти",$string);//
$string = ereg_replace("Zh","Ж",$string);
$string = ereg_replace("yo","ё",$string);
$string = ereg_replace("Yu","Ю",$string);
$string = ereg_replace("Ju","Ю",$string);
$string = ereg_replace("oo","у",$string);
$string = ereg_replace("ju","ю",$string);
$string = ereg_replace("yu","ю",$string);
$string = ereg_replace("sh","ш",$string);
$string = ereg_replace("yе","э",$string);
$string = ereg_replace("jа","я",$string);
$string = ereg_replace("yа","я",$string);
$string = ereg_replace("Wh","в",$string);
$string = ereg_replace("wh","в",$string);
$string = ereg_replace("th","с",$string);
$string = ereg_replace("Th","с",$string);
$string = ereg_replace("And","енд",$string);
$string = ereg_replace("and","енд",$string);
$string = ereg_replace("Baby","бейби",$string);
$string = ereg_replace("baby","бейби",$string);
$string = ereg_replace(" I "," ай ",$string);
$string = ereg_replace(" i "," ай ",$string);
$string = ereg_replace("You","ю",$string);
$string = ereg_replace("you","ю",$string);
$string = ereg_replace("How","Хау",$string);
$string = ereg_replace("how","хау",$string);
$string = ereg_replace("ge","дж",$string);
$string = ereg_replace("Love","лов",$string);
$string = ereg_replace("love","лов",$string);

$string = ereg_replace("Sh","Ш",$string);
$string = ereg_replace("Ch","Ч",$string);
$string = ereg_replace("ch","ч",$string);
$string = ereg_replace("ha","хе",$string);//
$string = ereg_replace("Ha","хе",$string);//
$string = ereg_replace("lu","лю",$string);
$string = ereg_replace("tely","тли",$string);
$string = ereg_replace("ee","и",$string);
$string = ereg_replace("Yo","Ё",$string);
$string = ereg_replace("Ya","Я",$string);
$string = ereg_replace("Ja","Я",$string);
$string = ereg_replace("Ye","е",$string);
$string = ereg_replace("Wa","Во",$string);
$string = ereg_replace("wa","во",$string);
$string = ereg_replace("ea","и",$string);
$string = ereg_replace("i","и",$string);
$string = ereg_replace("'","",$string);
$string = ereg_replace("c","к",$string);
$string = ereg_replace("u","а",$string);
$string = ereg_replace("x","кс",$string);
$string = ereg_replace("X","кс",$string);
$string = ereg_replace("k","к",$string);
$string = ereg_replace("e","е",$string);
$string = ereg_replace("n","н",$string);
$string = ereg_replace("g","г",$string);
$string = ereg_replace("J","Ж",$string);
$string = ereg_replace("j","ж",$string);
$string = ereg_replace("z","з",$string);
$string = ereg_replace("h","х",$string);
$string = ereg_replace("''","",$string);
$string = ereg_replace("f","ф",$string);
$string = ereg_replace("y","й",$string);
$string = ereg_replace("v","в",$string);
$string = ereg_replace("a","а",$string);
$string = ereg_replace("p","п",$string);
$string = ereg_replace("r","p",$string);
$string = ereg_replace("o","о",$string);
$string = ereg_replace("l","л",$string);
$string = ereg_replace("d","д",$string);
$string = ereg_replace("s","с",$string);
$string = ereg_replace("m","м",$string);
$string = ereg_replace("t","т",$string);
$string = ereg_replace("b","б",$string);
$string = ereg_replace("I","И",$string);
$string = ereg_replace("'","",$string);
$string = ereg_replace("C","К",$string);
$string = ereg_replace("U","У",$string);
$string = ereg_replace("K","К",$string);
$string = ereg_replace("E","Е",$string);
$string = ereg_replace("W","В",$string);
$string = ereg_replace("N","Н",$string);
$string = ereg_replace("w","в",$string);
$string = ereg_replace("G","Г",$string);
$string = ereg_replace("Z","З",$string);
$string = ereg_replace("H","Х",$string);
$string = ereg_replace("''","",$string);
$string = ereg_replace("F","Ф",$string);
$string = ereg_replace("Y","й",$string);
$string = ereg_replace("V","В",$string);
$string = ereg_replace("A","А",$string);
$string = ereg_replace("P","П",$string);
$string = ereg_replace("R","Р",$string);
$string = ereg_replace("O","О",$string);
$string = ereg_replace("L","Л",$string);
$string = ereg_replace("D","Д",$string);
$string = ereg_replace("S","С",$string);
$string = ereg_replace("M","М",$string);
$string = ereg_replace("I","И",$string);
$string = ereg_replace("T","Т",$string);
$string = ereg_replace("B","Б",$string);
return $string;
}

$result = mysql_query("SELECT * 
FROM clips_zar
LIMIT 25500 , 10000", $db); //аа
$row = mysql_fetch_array($result);
do{

$id = $row["id"];
$rus = str_replace("аа", "а", mb_strtolower(latrus($row["title"])));

 
$r = mysql_query (mb_convert_encoding("UPDATE clips_zar SET  ru='$rus' WHERE id='$id'", "utf-8", "windows-1251"));
 
}
while ($row = mysql_fetch_array($result));

echo latrus ("Beneath");
?>